Add docs for ACK default tags
aws-controllers-k8s/community pull request #1391
Opened 2022-07-14 21:55 UTC by vijtrip2

Description of changes:
* Add docs for ACK default tags

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-14 22:32 UTC, RedbackThomson commented on docs/content/docs/user-docs/ack-tags.md
> +and `services.k8s.aws/namespace`. *controller-version* tag value is the name of
```suggestion
and `services.k8s.aws/namespace`. The *controller-version* tag value is the name of
```

2022-07-14 22:32 UTC, RedbackThomson commented on docs/content/docs/user-docs/ack-tags.md
> +Example:
nit: Make into a header
```suggestion
### Example
```

2022-07-14 22:32 UTC, RedbackThomson commented on docs/content/docs/user-docs/ack-tags.md
> +  name: my-ack-tagging-bucket
Please add `namespace: default` so people can directly see that the tag value matches the metadata value

2022-07-14 22:32 UTC, RedbackThomson commented on docs/content/docs/user-docs/ack-tags.md
> +
Can we also call out which variable substitutions we allow?

2022-07-15 16:34 UTC, jaypipes requested changes
I'd like to see this actually be a tad more generic (see suggestions inline..)

2022-07-15 16:34 UTC, jaypipes commented on docs/content/docs/user-docs/ack-tags.md
> +title: "Managing ACK Default Tags"
I'm tempted to make this more generic... something like "Managing Tags on your AWS Resources"

2022-07-15 16:34 UTC, jaypipes commented on docs/content/docs/user-docs/ack-tags.md
> +managed by ACK controllers.
and then before this paragraph, say something to the effect of:

> Most AWS resources can have one or more Tags -- simple key/value pairs -- associated with them. These Tags allow you to organize and categorize your AWS resources for accounting and informational purposes. ACK custom resources (CRs) that support Tags will have a `Spec.Tags` field that store user-defined key/value pairs. In addition to user-defined Tags, ACK also supports a set of *default tags*, which are Tags that the ACK controller will automatically ensure are on all resources that it manages.

2022-07-15 16:34 UTC, jaypipes commented on docs/content/docs/user-docs/ack-tags.md
> +      value: "2"
Completely agree. :) Let's use one of the CRDs that has a `Tags` field that is either a `map[string]string` or `[]struct{}` type.

2022-07-29 17:45 UTC, jaypipes requested changes
Few minor grammar/nits otherwise looking great Vijay!

2022-07-29 17:45 UTC, jaypipes commented on docs/content/docs/user-docs/ack-tags.md
> +added in AWS resource alongside the tags from resource spec. Priority is given to
```suggestion
When tags are already present inside the Kubernetes custom resource's `Spec.Tags`, ACK default tags are
added to the AWS resource's tags collection along with those tags from `Spec.Tags`. Priority is given to
```

2022-07-29 17:45 UTC, jaypipes commented on docs/content/docs/user-docs/ack-tags.md
> +resource spec tags when there is a conflict between ACK default tag keys and tag
```suggestion
`Spec.Tags` when there is a conflict between ACK default tag keys and tag
```

2022-07-29 17:45 UTC, jaypipes commented on docs/content/docs/user-docs/ack-tags.md
> +keys in resource spec.
```suggestion
keys in `Spec.Tags`.
```

2022-07-29 17:45 UTC, jaypipes commented on docs/content/docs/user-docs/ack-tags.md
> +  will be expanded as "k8s-name=my-ack-tagging-repo"
```suggestion
  would be expanded to "k8s-name=my-ack-tagging-repo"
```

2022-07-29 17:55 UTC, jaypipes approved these changes
sweeeeeeeet. :)

2022-07-29 17:55 UTC, jaypipes commented
/lgtm

2022-07-29 17:56 UTC, merged