Technical feasibility k8 Secret for AuthToken
aws-controllers-k8s/community pull request #669
Opened 2021-01-29 19:42 UTC by nmvk

- Create a new SecretRef type
- Allow field config to declare a given field as secret
- Methods to allow fetching of secrets from k8 secrets.
- Automatic code generation to get the secret in sdk.go

Does not implement watcher which would be needed for the
update of an API.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-02-09 23:31 UTC, jaypipes requested changes
Hi @nmvk and @kumargauravsharma, please see my comments inline. This needs to be made to the github.com/aws-controllers-k8s/runtime repository to start and then we'll get to the changes that need to be made to the code-generator repo.

2021-02-09 23:31 UTC, jaypipes commented on templates/apis/types.go.tpl
> +}
this should be in the ACK core types (i.e. github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1). See my comment from above.

There should not be a need for a .HasSecret boolean field of the CRD.

2021-02-09 23:31 UTC, jaypipes commented on pkg/runtime/reconciler.go
> -	ref *corev1.SecretReference,
We should have an ACK core v1alpha1 type called `SecretKeyReference` that wraps the k8s `corev1.SecretReference` with an additional `Key` field.

Place this in a `github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1/secret.go` file:

```go
import (
    k8scorev1 "k8s.io/api/core/v1"
)

// SecretKeyReference combines a k8s corev1.SecretReference with a
// specific key within the referred-to Secret
type SecretKeyReference struct {
    k8scorev1.SecretReference
    // Key is the key within the secret
    Key string `json:"key"`
}
```

2021-02-23 05:26 UTC, nmvk commented
Closing this, below PRs have updated information
 
- https://github.com/aws-controllers-k8s/runtime/pull/5
- https://github.com/aws-controllers-k8s/code-generator/pull/21
- https://github.com/aws-controllers-k8s/elasticache-controller/pull/9

2021-02-23 05:26 UTC, closed without merging