update docs for separate ECR repos and releases
aws-controllers-k8s/community pull request #884
Opened 2021-08-02 18:49 UTC by jaypipes

Updates our documentation in order to have our new ECR Public
repositories exposed in appropriate links.

Removes the "Work in Progress" user documentation navigation and
adds our install, IRSA and Authorization user docs to the navigation
sidebar.

Updates the Services matrix with the most up-to-date links and statuses.

Finally, replaces the wording in the documentation index/homepage about
"Developer Preview" and "Not to use in production" with explanation
about our release process and maintenance phases and links to the
install docs.

Issue #829 

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

2021-08-02 18:56 UTC, surajkota approved these changes

2021-08-02 19:01 UTC, RedbackThomson requested changes
The installation instructions in `user-docs/install.md` still reference the old ECR public structure.

2021-08-02 20:06 UTC, vijtrip2 approved these changes

2021-08-02 20:06 UTC, vijtrip2 commented on docs/contents/index.md
> +our [project stages][proj-stages].
[proj-stages] ref missing from index.md

2021-08-02 22:56 UTC, jaypipes commented on docs/contents/index.md
> +our [project stages][proj-stages].
it's above on line 36 :)

2021-08-03 11:42 UTC, A-Hilaly approved these changes
Neat! :+1:

2021-08-03 12:33 UTC, jaypipes commented
@A-Hilaly care to lgtm? :)

2021-08-03 12:39 UTC, A-Hilaly commented
/lgtm

2021-08-03 12:39 UTC, merged